### ISSUE TITLE
Taar whitelist is not filtering out legacy addons 

### ISSUE THREAD

**Issue by crankycoder** [mozilla/taar-lite#18]
The TAAR dump is a complete list of addons, however that also includes legacy addons which no longer work post Fx57.

The taar whitelist needs to add an extra filter for is_webextension checking that this is set to true.

**Comment by crankycoder** [comment]
This patch is in https://github.com/mozilla/python_mozetl/pull/227

**Comment by mlopatka** [comment]
Just a point of clarification wrt this patch. In the current ETL flow, is the whitelist applied early enough that the coinstallation counts are not being skewed byut the presence of legacy addons?

The bottom line: is whitelist verification happening as early as it possible can be?
