### ISSUE TITLE
Taar-lite dev server is down

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/taar-lite#27]
STR:

1. Send a request to the taar-lite endpoint on -dev
```
https://taar.dev.mozaws.net/taarlite/api/v1/addon_recommendations/{73a6fe31-595d-460b-a920-fcc0f8843232}/
```
Actual result:
An internal server error is received

Expected result:
Add-on recommendations (if any) based on the request sent are received in the response

Notes:
- full error description:
```
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```
- reproduced only on the -dev server

**Comment by crankycoder** [comment]
The redis caching layer I put in had 2 separate bugs.  One was a  concurrency issue and the other was a performance issue.  I've since backed out the redis cache in favor of a process local caching strategy.

**Comment by AlexandraMoga** [comment]
Taar-lite dev server seems to be back on.
I'm marking this as verified fixed.
