### ISSUE TITLE
Does taar_lite_guiguid remove rare combinations?

### ISSUE THREAD

**Issue by birdsarah** [mozilla/taar-lite#51]
From the main README

```
taar_lite_guidguid.py

    Computes the coinstallation rate of each whitelisted addon with other whitelisted addons for a sample of Firefox clients
    Removes rare combinations of coinstallations
    writes guid_coinstallation.json
```

1) wanted to check that the ETL job acutally does remove rare combinations
2) if true, why are we doing a further pruning step?

**Comment by birdsarah** [comment]
ping @crankycoder

**Comment by dzeber** [comment]
No, it doens't actually do this. I've updated the README to reflect this in [this commit](https://github.com/mozilla/taar-lite/pull/45/commits/950962aaa5db9c06efb1a30f86b854da83b1ce2c) to the Docs PR #45 .
